services:
  - type: web
    name: medvision-frontend
    env: node
    plan: free
    buildCommand: rm -rf node_modules package-lock.json && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://medvision-ai-d10f.onrender.com/api
      - key: VITE_SOCKET_URL
        value: https://medvision-ai-d10f.onrender.com